# docker-compose.yml
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
