version: '3.8'

services:
  angular-app:
    image: node:18-alpine
    container_name: projet-angular
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build -- --configuration production && npx http-server ./dist/projet-recrutement-tuteurs-frontend -p 80"
    ports:
      - "80:80"
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
